### PR TITLE
add TOC to README.md

### LINKED ISSUE #80: Add TOC to README.md
**Is your feature request related to a problem? Please describe.**
Currently, the README is quite long and there is no TOC.

**Describe the solution you'd like**
A TOC will help provide easier navigation through the README.

**Describe alternatives you've considered**
N/A

**Additional context**
Screenshot:
image

### PR DESCRIPTION
**Pull request by jamesjose03**
## Issue that this pull request solves

Fixes: #80 

## Proposed changes

Added TOC to the README.md file.

## Types of changes

_Put an `x` in the boxes that apply_

-   [ ] Bugfix (non-breaking change which fixes an issue)
-   [ ] New feature (non-breaking change which adds functionality)
-   [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
-   [x] Documentation update (Documentation content changed)
-   [ ] Other (please describe): 

## Checklist

_Put an `x` in the boxes that apply_

-   [ ] My code follows the style guidelines of this project
-   [ ] I have performed a self-review of my own code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] I have made corresponding changes to the documentation
-   [ ] My changes generate no new warnings

## Screenshots

image

## Other information
N/A

### CODE REVIEW

**Review by samagragupta — DISMISSED** [review]

**Review by krharsh17 — COMMENTED** [review]
Please fix the code quality errors.

**Comment by jamesjose03** [comment]
I had added spaces but still, it shows errors.

**Review by ShivangiSingh17 — APPROVED** [review]

**Review by krharsh17 — APPROVED** [review]
Alright, let's ignore that then.

**Comment by jamesjose03** [comment]
@krharsh17 Thanks 👍

**Pull request merged**
