### PR TITLE
Migrate to Kotlin

### LINKED ISSUE #5: Convert project into kotlin
Before submitting a PR, ensure that your code is in level with the then code in the develop branch, and also that each and every java file has been converted into kotlin.

### PR DESCRIPTION
**Pull request by RaghavAwasthi**
Part of **GSSOC 2020** 🎉 ❤️
Migrates all the codebase to Kotlin without breaking any code. 
It will fix issue #5

### CODE REVIEW

**Comment by RaghavAwasthi** [comment]
@krharsh17  Codacy is giving a check failed for a function present in View Utils class which is redundant . This will get automatically resolved as soon as #7 will be addressed. 

PS:- Issue #7 is assigned to someone else so I am not addressing it in this PR

**Comment by Meghdut-Mandal** [comment]
Is someone assigned to this issue?

**Comment by krharsh17** [comment]
> Is someone assigned to this issue?

@RaghavAwasthi is already working on this issue.

**Review by saumya1singh — CHANGES_REQUESTED** [review]
Conflicts need to be resolved @RaghavAwasthi !

**Comment by krharsh17** [comment]
> Conflicts need to be resolved @RaghavAwasthi !

This PR has been put on hold for a few weeks @SaumyaSingh1 I should have put a label on it, my apologies.

**Comment by sidhuparas** [comment]
I think it would be early to shift this project to Kotlin but even after this, some decisions have to be made like findViewById is still being used however Kotlin Android Extensions are a better alternative. Again, there are other areas where improvements can be made to make code more readable with better practices.

**Comment by saumya1singh** [comment]
> > Conflicts need to be resolved @RaghavAwasthi !
> 
> This PR has been put on hold for a few weeks @SaumyaSingh1 I should have put a label on it, my apologies.

Oh okay @krharsh17! No issues :)

**Review by samagragupta — COMMENTED** [review]
Please resolve conflicts.

**Comment by sidhuparas** [comment]
@krharsh17 Do we have something planned for this? In GSSOC or post-GSSOC?

**Comment by saumya1singh** [comment]
> @krharsh17 Do we have something planned for this? In GSSOC or post-GSSOC?

++

**Comment by krharsh17** [comment]
@sidhuparas @SaumyaSingh1  Yes actually I think now is the right time to get this done. As the contributions season is almost over, we can finally migrate the project to kotlin

**Comment by sidhuparas** [comment]
@krharsh17 Cool. Then I think @RaghavAwasthi can fix the merge conflicts and we can move on to review the code.

**Comment by RaghavAwasthi** [comment]
I will update this by tonight

**Comment by krharsh17** [comment]
@RaghavAwasthi What's the update on this?

**Comment by RaghavAwasthi** [comment]
Updated the PR, Sincere Apologies for the delay.



[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
05/31/20,
10:05:27 PM

**Review by krharsh17 — APPROVED** [review]
I haven't gone through thoroughly but on a first look it seems right

**Pull request merged**
