### PR TITLE
Value tooltips radius

### LINKED ISSUE #13: Create an option to set the corner radius of the value tooltips

### PR DESCRIPTION
**Pull request by parthsharma07**
## Issue that this pull request solves

Fixes: #13 

## Proposed changes

Brief description of what is fixed or changed

## Types of changes

_Put an `x` in the boxes that apply_

-   [ ] Bugfix (non-breaking change which fixes an issue)
-   [x] New feature (non-breaking change which adds functionality)
-   [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
-   [ ] Documentation update (Documentation content changed)
-   [ ] Other (please describe): 

## Checklist

_Put an `x` in the boxes that apply_

-   [x] My code follows the style guidelines of this project
-   [x] I have performed a self-review of my own code
-   [x] I have commented my code, particularly in hard-to-understand areas
-   [x] I have made corresponding changes to the documentation
-   [x] My changes generate no new warnings

## Screenshots

Please attach the screenshots of the changes made in case of change in user interface
Screenshot_20200407-152308_BarView

## Other information

Any other information that is important to this pull request

### CODE REVIEW

**Comment by parthsharma07** [comment]
I couldn't figure out how to add a small triangle at the bottom of rectangular portion of background

**Comment by parthsharma07** [comment]
I couldn't figure out how to add a small triangle at the bottom of rectangular portion of background
drawable in the same bitmap using canvas drawing tools. I request the mentors to help me in solving
above problem.

**Comment by krharsh17** [comment]
I'm not sure whether I'll be a great help, @sidhuparas @SaumyaSingh1 Could you guys please look into it?

**Comment by sidhuparas** [comment]
@krharsh17 Sure, me and @SaumyaSingh1 will coordinate with @parthsharma07.

@parthsharma07 Can you please describe a little more? Actually I wasn't watching this issue/PR so don't have any context for the same. Do you want triangle at the bottom inside the rectangle (of value which is cornered), right? And why?

**Comment by saumya1singh** [comment]
> I couldn't figure out how to add a small triangle at the bottom of rectangular portion of background
> drawable in the same bitmap using canvas drawing tools. I request the mentors to help me in solving
> above problem.

Sure @parthsharma07, the issue that you wanted to fix states _Create an option to set the corner radius of the value tooltips_. The screenshot that you attached seems to set the corner radius.
Then why you want to add triangle?🤔

**Comment by krharsh17** [comment]
Any progress on this @parthsharma07 ?

**Comment by parthsharma07** [comment]
> @krharsh17 Sure, me and @SaumyaSingh1 will coordinate with @parthsharma07.
> 
> @parthsharma07 Can you please describe a little more? Actually I wasn't watching this issue/PR so don't have any context for the same. Do you want triangle at the bottom inside the rectangle (of value which is cornered), right? And why?

No I want a triangle at the bottom of rectangle outside it because its a part of the design

**Comment by parthsharma07** [comment]
> > I couldn't figure out how to add a small triangle at the bottom of rectangular portion of background
> > drawable in the same bitmap using canvas drawing tools. I request the mentors to help me in solving
> > above problem.
> 
> Sure @parthsharma07, the issue that you wanted to fix states _Create an option to set the corner radius of the value tooltips_. The screenshot that you attached seems to set the corner radius.
> Then why you want to add triangle?🤔

let me show you a screenshot of actual design

**Comment by parthsharma07** [comment]
Screenshot (136)_LI
I want to add that small triangle at the bottom which I circled in the image

**Comment by parthsharma07** [comment]
> Any progress on this @parthsharma07 ?

Still stuck with that triangle part. Its not appearing at proper place with all the methods I tried

**Review by krharsh17 — APPROVED** [review]
I'm gonna merge this just so you get the points in the leaderboard

**Pull request merged**
