### PR TITLE
Fixed #12 : Fix to Screen_Width so that BarView doesn't run out of the screen

### LINKED ISSUE #12: [BUG] Configure the width of the bars so that they fit inside the screen even at max length
Currently, on some screens, the width of the bar exceeds the screen width, due to which the values are not visible on the screen

### PR DESCRIPTION
**Pull request by DarthBenro008**
This is a PR to Issue #12
Fixed the BarView going out of bounds on some Display.
Tested on Redmi 3S and OnePlus 6T

**Before Fix:**

beforeFix

**After Fix:**

afterFix

### CODE REVIEW

**Comment by krharsh17** [comment]
@Sourish-Mukherjee Check this fix on your device and let me know if it's working for you or not

**Comment by Sourish-Mukherjee** [comment]
@krharsh17 
It's working fine on Asus Max Pro M1. 👍

Except, I think  he changed Apple to **1f** for testing purpose but forgot to revert it back, Samsung has a greater market share 

WhatsApp Image 2020-03-05 at 1 20 00 AM

**Comment by DarthBenro008** [comment]
@Sourish-Mukherjee i did not revert it back as i thought the developer should get an idea what it would look like at max length , and also the fact i did not know it was statistically placed. Nevertheless , Both Apple and Samsung have equal Global Share Market and the others column leads statistically.
Source: https://www.counterpointresearch.com/global-smartphone-share/

**Comment by Sourish-Mukherjee** [comment]
It's not about market share, I m saying in the given data Samsung has a greater dummy percentage value but the bar graph is smaller than Apple's.

**Review by krharsh17 — APPROVED** [review]

**Pull request merged**
