### PR TITLE
Fixed #25 : added getters and setters

### LINKED ISSUE #25: Define setter & getter functions for all propery fields in the barview class
Define appropriate public setters/getters for these fields
```
BAR_MARGIN
VERTICAL_SPACING
BAR_HEIGHT
LABEL_FONT_SIZE
VALUE_FONT_SIZE
LABEL_TEXT_COLOR
VALUE_TEXT_COLOR
RIPPLE_COLOUR
```

### PR DESCRIPTION
**Pull request by dino-saurabh**
added public getters and setters for the "BarView class"  which Closes #25 .

### CODE REVIEW

**Comment by dino-saurabh** [comment]
@krharsh17 should we change the attributes names also since these arent constants but are in all caps
??

**Comment by krharsh17** [comment]
> @krharsh17 should we change the attributes names also since these arent constants but are in all caps
??

I think we'll have to do this. Otherwise, the setter functions would look weird 😅

**Comment by krharsh17** [comment]
Fixing the names would also solve the Code Quality errors, so I guess that will have to be compulsorily done.

**Comment by dino-saurabh** [comment]
Should I add another commit to my PR??

**Comment by krharsh17** [comment]
Yes, and squash the two into one

**Pull request closed without merging**
