### PR TITLE
Added Feature to Automatically Build Testing Apks

### LINKED ISSUE #41: Automatically Building and Updating  Sample APK
**Is your feature request related to a problem? Please describe.**
It would be good if we Rebuild an APK on every merge into the Develop branch and Master Branch.
This way it would be easy for user to test the application without having any hassle. 

**Describe the solution you'd like**
We can use the Automatic Code Building by CI/CD Pipelines to build a development APK and push it to the APK Branch.
We can use the build output directories generated by the Trevor CI and copy the APK file from there using a simple upload script and then use git CLI interface available in the Trevor to upload the apk to our branch using our Github API KEY.

**Describe alternatives you've considered**
I guess Travis CI and Circle CI are quite good alternatives to address the above problem

I would like to work on this issue

### PR DESCRIPTION
**Pull request by RaghavAwasthi**
# Warning
*Please merge #59 before merging this PR*
# Feature
This PR adds a feature to Automatically build Apks when a Pull Request is merged into the master branch/ develop branch.It will fix #41 
## Additional Step
@krharsh17 
Please Add a Personal Access Token to Travis CI Environment Variable.
Follow these steps.
1 - Create your Personal Access token by following this guide
      https://help.github.com/en/github/authenticating-to-github/creating-a-personal-access-token- 
      for-the-command-line
2 - Add that generated token to Travis CI Environment Variable with the name `GITHUB_KEY` .

### CODE REVIEW

**Review by ShivangiSingh17 — CHANGES_REQUESTED** [review]
@RaghavAwasthi Please parse yml file through YAML Formatter, the .travis.yml have basic indentation related syntax issues.
Also if you already adding the .travis.yml file through #59 then what's the need of adding it again in this PR?

**Comment by RaghavAwasthi** [comment]
@ShivangiSingh17 Are you sure that `travis.yml` file has syntax issues. The Travis is building fine on the fork and generating Apk as well.
Build log:-https://travis-ci.com/github/RaghavAwasthi/barview-android/builds/154100914
Anyways I have parsed the YAML file as you asked.

**Review by ShivangiSingh17 — APPROVED** [review]
Good work!!

**Review by samagragupta — APPROVED** [review]

**Review by krharsh17 — COMMENTED** [review]
I've merged it, but we'll have to see it in action before we're fully sure that it works

**Pull request merged**
